import 'package:custom_books/core/apptheme/apptheme.dart';
import 'package:custom_books/core/utils/dimensions.dart';
import 'package:custom_books/core/widgets/custom_sliver_appbar.dart';
import 'package:flutter/material.dart';

class TermsOfServicePage extends StatelessWidget {
  const TermsOfServicePage({super.key});

  @override
  Widget build(BuildContext context) {
    Dimensions.init(context);

    return Scaffold(
      backgroundColor: context.colors.background,
      body: SafeArea(
        child: CustomScrollView(
          physics: const BouncingScrollPhysics(),
          slivers: [
            const CustomSliverAppBar(
              title: 'Terms of Service',
              leadingType: AppBarLeadingType.back,
            ),
            SliverPadding(
              padding: EdgeInsets.symmetric(horizontal: Dimensions.width20),
              sliver: SliverList(
                delegate: SliverChildListDelegate([
                  SizedBox(height: Dimensions.height15),
                  Text(
                    'Last updated: August 2026',
                    style: TextStyle(
                      fontSize: Dimensions.font16 * 0.8,
                      color: context.colors.textTertiary,
                    ),
                  ),
                  SizedBox(height: Dimensions.height20),
                  _buildSection(
                    context,
                    title: '1. Acceptance of Terms',
                    content:
                        'By downloading, installing, or using Custom Books, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the application.',
                  ),
                  _buildSection(
                    context,
                    title: '2. Description of Service',
                    content:
                        'Custom Books is an accounting and invoicing application designed for small businesses. The service includes features for managing customers, vendors, invoices, bills, expenses, inventory, and financial reporting.',
                  ),
                  _buildSection(
                    context,
                    title: '3. User Responsibilities',
                    content:
                        'You are responsible for maintaining the accuracy of data entered into the application. You agree to use the service only for lawful purposes and in accordance with applicable accounting regulations in your jurisdiction.',
                  ),
                  _buildSection(
                    context,
                    title: '4. Intellectual Property',
                    content:
                        'The Custom Books application, including its design, code, and content, is the intellectual property of Tech Geum Private Limited. You are granted a non-exclusive, non-transferable license to use the application for its intended purpose.',
                  ),
                  _buildSection(
                    context,
                    title: '5. Data Ownership',
                    content:
                        'You retain full ownership of all financial data, customer information, and business records you enter into Custom Books. We do not claim any ownership rights over your data.',
                  ),
                  _buildSection(
                    context,
                    title: '6. Limitation of Liability',
                    content:
                        'Custom Books is provided "as is" without warranties of any kind. Tech Geum Private Limited shall not be liable for any financial decisions made based on reports generated by the application. Always consult a qualified accountant for professional advice.',
                  ),
                  _buildSection(
                    context,
                    title: '7. Termination',
                    content:
                        'You may stop using Custom Books at any time by uninstalling the application. We reserve the right to terminate or suspend access to the service for violations of these terms.',
                  ),
                  _buildSection(
                    context,
                    title: '8. Changes to Terms',
                    content:
                        'We reserve the right to modify these Terms of Service at any time. Continued use of the application after changes constitutes acceptance of the new terms.',
                  ),
                  _buildSection(
                    context,
                    title: '9. Contact',
                    content:
                        'For questions about these Terms of Service, contact us at:\n\nEmail: sirajulhaq3154@gmail.com\nPhone: +91 96054 55758\n\nTech Geum Private Limited',
                  ),
                  SizedBox(height: Dimensions.height30),
                ]),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSection(
    BuildContext context, {
    required String title,
    required String content,
  }) {
    return Padding(
      padding: EdgeInsets.only(bottom: Dimensions.height20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: TextStyle(
              fontSize: Dimensions.font16,
              fontWeight: FontWeight.w700,
              color: context.colors.textPrimary,
            ),
          ),
          SizedBox(height: Dimensions.height10),
          Text(
            content,
            style: TextStyle(
              fontSize: Dimensions.font16 * 0.85,
              color: context.colors.textSecondary,
              height: 1.6,
            ),
          ),
        ],
      ),
    );
  }
}
